//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AreaManager.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjectLocation
    {
        public long Id { get; set; }
        public Nullable<byte> ObjectType { get; set; }
        public Nullable<long> ObjectId { get; set; }
        public Nullable<float> Longitude { get; set; }
        public Nullable<float> Latitude { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
    }
}
